version: '2'
services:
  main_app:
    image: bennischober/remix-portfolio
    container_name: remix_portfolio
    ports:
      - "3000:3000"
    volumes:
      - /var/www/benjaminschober.de/content:/content
